parameters:
#    androfony.example.class: Androfony\AndrofonyBundle\Example

services:
#    androfony.example:
#        class: %androfony.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
